### ISSUE TITLE
errexits on line 15 and 113

### ISSUE THREAD

**Issue by secureyourself7** [brianddk/trezor-tails#2]
I use Tails 4.2.2 and I got this:
errexit on line 15 /tmp/trezor-tails/modules/25_python_trezor
errexit on line 113 /dev/fd/63
Full console output: 

amnesia@amnesia:~$ bash <(wget -O- https://raw.githubusercontent.com/brianddk/trezor-tails/master/bootstrap.sh)

Redirecting output to ‘wget-log’.
18496 (process ID) old priority 0, new priority 19
/tmp ~
Cloning into 'trezor-tails'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (100/100), done.
remote: Total 524 (delta 75), reused 60 (delta 26), pack-reused 391
Receiving objects: 100% (524/524), 111.08 KiB | 972.00 KiB/s, done.
Resolving deltas: 100% (315/315), done.
#### calling udev_s1 ####
--2020-01-18 03:38:35--  https://raw.githubusercontent.com/trezor/trezor-common/master/udev/51-trezor.rules
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 978 [text/plain]
Saving to: ‘/tmp/trezor-tails/assets/udev/51-trezor.rules’

51-trezor.rules     100%[===================>]     978  --.-KB/s    in 0s      

2020-01-18 03:38:36 (24.1 MB/s) - ‘/tmp/trezor-tails/assets/udev/51-trezor.rules’ saved [978/978]

--2020-01-18 03:38:36--  https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/20-hw1.rules
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.128.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.128.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1481 (1.4K) [text/plain]
Saving to: ‘/tmp/trezor-tails/assets/udev/20-hw1.rules’

20-hw1.rules        100%[===================>]   1.45K  --.-KB/s    in 0s      

2020-01-18 03:38:37 (41.7 MB/s) - ‘/tmp/trezor-tails/assets/udev/20-hw1.rules’ saved [1481/1481]

#### calling python_trezor_s1 ####
/tmp/trezor-tails/assets/hidapi /tmp/trezor-tails/assets ~
--2020-01-18 03:38:37--  http://http.us.debian.org/debian/pool/main/s/systemd/libudev1_241-5~bpo9+1_amd64.deb
Resolving http.us.debian.org (http.us.debian.org)... 208.80.154.15
Connecting to http.us.debian.org (http.us.debian.org)|208.80.154.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 149744 (146K) [application/octet-stream]
Saving to: ‘libudev1_241-5~bpo9+1_amd64.deb’

libudev1_241-5~bpo9 100%[===================>] 146.23K   436KB/s    in 0.3s    

2020-01-18 03:38:38 (436 KB/s) - ‘libudev1_241-5~bpo9+1_amd64.deb’ saved [149744/149744]

--2020-01-18 03:38:38--  http://http.us.debian.org/debian/pool/main/s/systemd/udev_241-5~bpo9+1_amd64.deb
Resolving http.us.debian.org (http.us.debian.org)... 208.80.154.15
Connecting to http.us.debian.org (http.us.debian.org)|208.80.154.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1289930 (1.2M) [application/octet-stream]
Saving to: ‘udev_241-5~bpo9+1_amd64.deb’

udev_241-5~bpo9+1_a 100%[===================>]   1.23M  1.23MB/s    in 1.0s    

2020-01-18 03:38:39 (1.23 MB/s) - ‘udev_241-5~bpo9+1_amd64.deb’ saved [1289930/1289930]

--2020-01-18 03:38:39--  http://http.us.debian.org/debian/pool/main/s/systemd/libudev-dev_241-5~bpo9+1_amd64.deb
Resolving http.us.debian.org (http.us.debian.org)... 208.80.154.15
Connecting to http.us.debian.org (http.us.debian.org)|208.80.154.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 108672 (106K) [application/octet-stream]
Saving to: ‘libudev-dev_241-5~bpo9+1_amd64.deb’

libudev-dev_241-5~b 100%[===================>] 106.12K   309KB/s    in 0.3s    

2020-01-18 03:38:40 (309 KB/s) - ‘libudev-dev_241-5~bpo9+1_amd64.deb’ saved [108672/108672]

/tmp/trezor-tails/assets ~
#### calling bridge_s1 ####
--2020-01-18 03:38:40--  https://rusnak.io/public/pgp.txt
Resolving rusnak.io (rusnak.io)... 185.199.108.153
Connecting to rusnak.io (rusnak.io)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55614 (54K) [text/plain]
Saving to: ‘/tmp/trezor-tails/assets/rusnak.asc’

/tmp/trezor-tails/a 100%[===================>]  54.31K   183KB/s    in 0.3s    

2020-01-18 03:38:51 (183 KB/s) - ‘/tmp/trezor-tails/assets/rusnak.asc’ saved [55614/55614]

--2020-01-18 03:38:51--  https://github.com/trezor/webwallet-data/raw/master/bridge/2.0.27/trezor-bridge_2.0.27_amd64.deb
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://media.githubusercontent.com/media/trezor/webwallet-data/master/bridge/2.0.27/trezor-bridge_2.0.27_amd64.deb [following]
--2020-01-18 03:38:52--  https://media.githubusercontent.com/media/trezor/webwallet-data/master/bridge/2.0.27/trezor-bridge_2.0.27_amd64.deb
Resolving media.githubusercontent.com (media.githubusercontent.com)... 199.232.36.133
Connecting to media.githubusercontent.com (media.githubusercontent.com)|199.232.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5066994 (4.8M) [application/octet-stream]
Saving to: ‘/tmp/trezor-tails/assets/trezor-bridge_2.0.27_amd64.deb’

trezor-bridge_2.0.2 100%[===================>]   4.83M  1.38MB/s    in 3.8s    

2020-01-18 03:38:58 (1.26 MB/s) - ‘/tmp/trezor-tails/assets/trezor-bridge_2.0.27_amd64.deb’ saved [5066994/5066994]

gpg: key 0x91F3B339B9A02A3D: 62 signatures not checked due to missing keys
gpg: key 0x91F3B339B9A02A3D: "Pavol Rusnák <pavol@rusnak.io>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg (GnuPG) 2.2.12; Copyright (C) 2018 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

pub  rsa4096/0x91F3B339B9A02A3D
     created: 2012-03-07  expires: 2021-01-14  usage: SC  
     trust: ultimate      validity: ultimate
sub  rsa4096/0x22AF226D38DC1F4D
     created: 2012-03-07  expires: 2021-01-14  usage: E   
[ultimate] (1). Pavol Rusnák <pavol@rusnak.io>
[ultimate] (2)  Pavol Rusnák <stick@gk2.sk>
[ultimate] (3)  Pavol Rusnák <stick@satoshilabs.com>
[ultimate] (4)  Pavol Rusnák <prusnak@opensuse.org>
[ultimate] (5)  [jpeg image of size 2449]

pub  rsa4096/0x91F3B339B9A02A3D
     created: 2012-03-07  expires: 2021-01-14  usage: SC  
     trust: ultimate      validity: ultimate
sub  rsa4096/0x22AF226D38DC1F4D
     created: 2012-03-07  expires: 2021-01-14  usage: E   
[ultimate] (1). Pavol Rusnák <pavol@rusnak.io>
[ultimate] (2)  Pavol Rusnák <stick@gk2.sk>
[ultimate] (3)  Pavol Rusnák <stick@satoshilabs.com>
[ultimate] (4)  Pavol Rusnák <prusnak@opensuse.org>
[ultimate] (5)  [jpeg image of size 2449]

Please decide how far you trust this user to correctly verify other users' keys
(by looking at passports, checking fingerprints from different sources, etc.)

  1 = I don't know or won't say
  2 = I do NOT trust
  3 = I trust marginally
  4 = I trust fully
  5 = I trust ultimately
  m = back to the main menu

pub  rsa4096/0x91F3B339B9A02A3D
     created: 2012-03-07  expires: 2021-01-14  usage: SC  
     trust: ultimate      validity: ultimate
sub  rsa4096/0x22AF226D38DC1F4D
     created: 2012-03-07  expires: 2021-01-14  usage: E   
[ultimate] (1). Pavol Rusnák <pavol@rusnak.io>
[ultimate] (2)  Pavol Rusnák <stick@gk2.sk>
[ultimate] (3)  Pavol Rusnák <stick@satoshilabs.com>
[ultimate] (4)  Pavol Rusnák <prusnak@opensuse.org>
[ultimate] (5)  [jpeg image of size 2449]

#### calling electron_bch_s1 ####
sending incremental file list
./
.bash_profile
.bashrc
.config/
.config/chromium/
.config/chromium/First Run
.config/chromium/Local State
.config/chromium/Default/
.config/chromium/Default/Preferences
.config/dconf/
.config/dconf/user

sent 11,223 bytes  received 157 bytes  22,760.00 bytes/sec
total size is 10,571  speedup is 0.93
[sudo] password for amnesia: 
20554 (process ID) old priority 19, new priority 19
#### calling swap_s2 ####
swapon.distrib: /live/persistence/TailsData_unlocked/swapfile: found signature [pagesize=4096, signature=swap]
swapon.distrib: /live/persistence/TailsData_unlocked/swapfile: pagesize=4096, swapsize=1073741824, devsize=1073741824
swapon /live/persistence/TailsData_unlocked/swapfile
#### calling python_trezor_s2 ####
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Err:2 http://dl.google.com/linux/chrome/deb stable Release
  Unsupported proxy configured: socks5://127.0.0.1:9050
Hit:3 tor+http://jenw7xbd6tf7vfhp.onion 4.2.2 InRelease                        
Hit:4 tor+http://sgvtcaew4bxjd7ln.onion buster/updates InRelease               
Hit:5 tor+http://vwakviie2ienjx6t.onion/debian buster InRelease     
Hit:6 tor+http://sdscoq7snqtznauu.onion/torproject.org buster InRelease
Hit:7 tor+http://vwakviie2ienjx6t.onion/debian bullseye InRelease
Hit:8 tor+http://vwakviie2ienjx6t.onion/debian sid InRelease
Reading package lists... Done
E: The repository 'http://dl.google.com/linux/chrome/deb stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
errexit on line 15 /tmp/trezor-tails/modules/25_python_trezor
errexit on line 113 /dev/fd/63

**Comment by brianddk** [comment]
Thx for the update... I've been putting off the changes for Tails 4.x (buster) from tails 3.x (stretch).  I've now completed the changes based on Tails 4.5.  If you update to 4.5 it should work now.

Keep in mind, that you might want to try his on a scratch tails image first.  Results may vary :(

**Comment by brianddk** [comment]
I'm assuming that [release v1.0](https://github.com/brianddk/trezor-tails/releases/tag/v1.0) resolves this issue.  I'll close it, but please re-open if I misinterpreted your findings.

**Comment by brianddk** [comment]
I'm assuming that [release v1.0](https://github.com/brianddk/trezor-tails/releases/tag/v1.0) resolves this issue.  I'll close it, but please re-open if I misinterpreted your findings.
